
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Merve
 */
public class tablo extends javax.swing.JFrame {

    /**
     * Creates new form tablo
     */
    DefaultTableModel tablo = new DefaultTableModel ();
   
    
    public tablo() {
        initComponents();
        gösterge_tablosu.setModel (tablo);
        tablo.setColumnIdentifiers(new String[] {"Ad", "Soyad", "Numara","Plaka","Saat"} );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sys_soyad = new javax.swing.JTextField();
        sys_ad = new javax.swing.JTextField();
        sys_numara = new javax.swing.JTextField();
        sys_plaka = new javax.swing.JTextField();
        sys_giris_saati = new javax.swing.JTextField();
        btn_giris = new javax.swing.JButton();
        btn_iptal = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();
        btn_sonlandir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gösterge_tablosu = new javax.swing.JTable();
        guncelle_btn = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JLabel();
        sil_buton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müşteri Giriş");
        setLocation(new java.awt.Point(250, 100));

        jLabel2.setText("Müşteri Adı:");

        jLabel3.setText("Müşteri Soyadı:");

        jLabel4.setText("Numara:");

        jLabel5.setText("Araç  Plakası:");

        jLabel6.setText("Giriş Saati:");

        sys_ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sys_adActionPerformed(evt);
            }
        });

        sys_plaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sys_plakaActionPerformed(evt);
            }
        });

        btn_giris.setBackground(new java.awt.Color(102, 204, 255));
        btn_giris.setText("Kayıt Ol");
        btn_giris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });

        btn_iptal.setBackground(new java.awt.Color(255, 0, 0));
        btn_iptal.setText("İptal ");
        btn_iptal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iptalActionPerformed(evt);
            }
        });

        btn_cikis.setBackground(new java.awt.Color(51, 255, 51));
        btn_cikis.setText("Çıkış Yap");
        btn_cikis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        btn_sonlandir.setBackground(new java.awt.Color(255, 0, 0));
        btn_sonlandir.setText("Sistemi Sonlandır");
        btn_sonlandir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sonlandir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sonlandirActionPerformed(evt);
            }
        });

        gösterge_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gösterge_tablosu);

        guncelle_btn.setText("Bilgileri Güncelle");
        guncelle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_btnActionPerformed(evt);
            }
        });

        mesaj_yazisi.setForeground(new java.awt.Color(0, 0, 204));

        sil_buton.setText("Girilen Kaydı Sil");
        sil_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_giris, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cikis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_sonlandir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(btn_iptal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sys_soyad)
                            .addComponent(sys_numara, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(sys_ad)
                            .addComponent(sys_plaka)
                            .addComponent(sys_giris_saati)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sys_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sys_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sys_numara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sys_plaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sys_giris_saati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(guncelle_btn)
                        .addGap(3, 3, 3)))
                .addComponent(btn_giris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_iptal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_sonlandir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sil_buton)
                        .addGap(62, 62, 62))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sys_adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sys_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sys_adActionPerformed

    private void sys_plakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sys_plakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sys_plakaActionPerformed

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed
        // TODO add your handling code here:
        String ad= sys_ad.getText();
        String soyad= sys_soyad.getText();
        String numara= sys_numara.getText();
        String plaka=sys_plaka.getText();
        String saat= sys_giris_saati.getText();
        sys_ad.setText ("");
        sys_soyad.setText ("");
        sys_numara.setText ("");
        sys_plaka.setText ("");
        sys_giris_saati.setText("");
      
        String save_message = "Kayıt Tamamlandı";
        JOptionPane.showMessageDialog(rootPane, save_message);
        
        
        tablo.addRow(new String [] {ad, soyad, numara, plaka, saat});
        
       
      
    }//GEN-LAST:event_btn_girisActionPerformed

    private void btn_iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iptalActionPerformed
        sys_ad.setText ("");
        sys_soyad.setText ("");
        sys_numara.setText ("");
        sys_plaka.setText ("");
        sys_giris_saati.setText("");
      
        
    }//GEN-LAST:event_btn_iptalActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        Double hesap;
        String giris_saati =JOptionPane.showInputDialog( "Giriş Saati");
        String çıkış_saati =JOptionPane.showInputDialog( "Çıkış Saati");
        Double grş_st=Double.parseDouble(giris_saati);
        Double çkş_st=Double.parseDouble(çıkış_saati);
        Double saat_farkı=(çkş_st- grş_st) ;
        hesap = saat_farkı *15 ;
        JOptionPane.showMessageDialog(rootPane,"Tutar: "+String.valueOf(hesap));
        tablo.removeRow(gösterge_tablosu.getSelectedRow());
        
        
        
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void btn_sonlandirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sonlandirActionPerformed
        dispose();
    }//GEN-LAST:event_btn_sonlandirActionPerformed

    private void guncelle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_btnActionPerformed
     
                mesaj_yazisi.setText("");

        DefaultTableModel model = (DefaultTableModel) gösterge_tablosu.getModel();
        
        int secili_row = gösterge_tablosu.getSelectedRow();
        
        if (secili_row == -1) {
            
            if (gösterge_tablosu.getRowCount() == 0 ) {
                
                mesaj_yazisi.setText("tablo suan boş....");
            }
            else {
                
                mesaj_yazisi.setText("lütfen guncellenecek urun secınız..");
            }
        }
        else {
            
            model.setValueAt(sys_ad.getText(),secili_row,0);
            model.setValueAt(sys_soyad.getText(),secili_row,1);
            
            model.setValueAt(sys_numara.getText(),secili_row,2);
             model.setValueAt(sys_plaka.getText(),secili_row,3);
              model.setValueAt(sys_giris_saati.getText(),secili_row,4);


            
            mesaj_yazisi.setText("Güncellendi...");
            
        }
    }//GEN-LAST:event_guncelle_btnActionPerformed

    private void sil_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonActionPerformed
        mesaj_yazisi.setText("");
        
        DefaultTableModel model = (DefaultTableModel) gösterge_tablosu.getModel();
        
        int secili_row = gösterge_tablosu.getSelectedRow();
        
        if (secili_row == -1) {
            if (gösterge_tablosu.getRowCount() == 0 ) {
                
                mesaj_yazisi.setText("tablo bos.");
            }
            else {
                
                mesaj_yazisi.setText("silinecek bir alan sec...");
            }
        }
        else {
            
            model.removeRow(secili_row);
            
            mesaj_yazisi.setText("basarıyla silindi...");
        }
    }//GEN-LAST:event_sil_butonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_giris;
    private javax.swing.JButton btn_iptal;
    private javax.swing.JButton btn_sonlandir;
    private javax.swing.JButton guncelle_btn;
    private javax.swing.JTable gösterge_tablosu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton sil_buton;
    private javax.swing.JTextField sys_ad;
    private javax.swing.JTextField sys_giris_saati;
    private javax.swing.JTextField sys_numara;
    private javax.swing.JTextField sys_plaka;
    private javax.swing.JTextField sys_soyad;
    // End of variables declaration//GEN-END:variables
}
